name: Testing2 before deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  # Build job
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Install dependencies 
        run: npm ci
      - name: Run tests
        run: npm test
      
  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages' 
    # - id: build-publish
    # - name: Deploy to GitHub Pages
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./static
    - id: build-publish
      env:
        CI: false
      uses: bitovi/github-actions-react-to-github-pages@v1.2.2
      with:
        # path: ./static 
        path: .

      